[common.logging_config]
disable_existing_loggers = false
version = 1

[common.logging_config.formatters.default]
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[common.logging_config.handlers.console]
class = "logging.StreamHandler"
formatter = "default"
level = "DEBUG"
stream = "ext://sys.stdout"

[common.logging_config.root]
handlers = ["console"]
level = "WARNING"
